# Generated by Django 3.1.7 on 2021-06-01 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='json',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
