# Generated by Django 3.1.7 on 2021-06-01 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0002_json_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bootstrap',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='css',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='html',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='js',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='python',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='rest',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
