# Generated by Django 3.1.7 on 2021-06-01 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0004_auto_20210601_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bootstrap',
            name='definition',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='css',
            name='definition',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='django',
            name='definition',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='json',
            name='definition',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='python',
            name='definition',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='rest',
            name='definition',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
