# Generated by Django 3.1.7 on 2021-06-02 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0005_auto_20210601_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='html',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/pics'),
        ),
    ]
